:bug: Fix after-message overwriting

diff --git a/vim/install b/vim/install
--- a/vim/install
+++ b/vim/install
@@ -5,17 +5,23 @@ source script/helpers
 
 set -e
 
+function ensure_folder {
+  if ! [ -d "$1" ];then
+    mkdir -p "$1"
+  fi
+}
+
 if [ -z ${DOTUPDATE+x} ];then
   rm -rf "${HOME}/.vim"
   git clone --recursive https://github.com/carlhuda/janus.git "${HOME}/.vim" -q \
     || die "Could not clone janus into ${HOME}/.vim"
 
   pushq "${HOME}/.vim" || die "Could not go into the ${HOME}/.vim"
-  rake update folders >/dev/null || die "Rake failed."
+  rake update folders >/dev/null 2>&1 || die "Rake failed."
   popq
 else
   pushq "${HOME}/.vim" || die "Could not go into the ${HOME}/.vim"
-  rake update >/dev/null || die "Rake failed."
+  rake update >/dev/null 2>&1 || die "Rake failed."
   popq
 fi
 
